apiVersion: apps/v1
kind: Deployment
metadata:
  name: cumulusbanksmssvc
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cumulusbanksmssvc
  template:
    metadata:
      labels:
        name: cumulusbanksmssvc
    spec:
      serviceAccountName: cumulusbanksmssvc
      containers:
        - name: cumulusbanksmssvc
          # Replace this with the built image name
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cumulusbanksmssvc"
