replicaCount: 2
namespace: "kubeapp"
sms:
  accountsid: "xxx"
  authtoken: "xxx"
  sendernumber: "xxx"
metadata:
 name: sms-svc 
 label: sms-svc
readinessProbe:
  path: /healthz
  port: 3003
  initialDelaySeconds: 10
  timeoutSeconds: 2
  periodSeconds: 10

livenessProbe:
  path: /healthz
  port: 3003
  initialDelaySeconds: 10
  timeoutSeconds: 2
  periodSeconds: 10
image:
  name: sms-svc
  imageName: "sms-svc" 
  imagePullPolicy: Always
  ports:
    containerPort: 3003
  requests:
    cpu: "50m"
    memory: "150Mi"
  limits:
    cpu: "80m"
    memory: "200Mi"
  maxSurge: 1
  maxUnavailable: 0
  lifecycle:
    preStop:
      command: ["/bin/bash", "-c", "sleep 20"]
  
hpa:
  metadata:
    name: sms-svcmicroservicehpa
  spec:
    maxReplicas: 10
    minReplicas: 2
  metrics:
    pods:
      targetAverageValue: 30
    resource:
      name: cpu
      targetAverageUtilization: 50
    memory:
      targetAverageUtilization: 50
  scaleTargetRef:  
    name: sms-svc

envOfConfigmaps:
  envaccountSid:
    name: accountSid
    configMapKeyRef:
      name: cumulusbanksms
      key: accountSid
  envauthToken:
    name: authToken
    configMapKeyRef:
      name: cumulusbanksms
      key: authToken
  envsenderNumber:
    name: senderNumber
    configMapKeyRef:
      name: cumulusbanksms
      key: senderNumber

service:
  serviceMetadata:
    name: sms-svc
    labels:
      app: sms-svc
  selector:
    selectorName: sms-svc
  servicePortConfiguration:
    protocol: TCP
    name: sms-svc
    type: ClusterIP
    port: 3003
    targetPort: 3003

imagestream:
  name:  sms-svc
  label: sms-svc

buildconfig:
  uri: "https://github.com/cumulus-bank/SMS-Microservice.git"
  branch: "master"
  name: "sms-svc"
  imagename: "sms-svc:latest"
  secret1: "racsgvhbjndk"
  secret2: "racsgvhbjndk"


routes:
  host: "sms-svc-kubeapp.apps.9.30.210.207.nip.io"
  targetPort: 3003
  name: sms-svc
  weight: 100


nameOverride: ""
fullnameOverride: ""